### ISSUE TITLE
[FEATURE] More types of windowing

### ISSUE THREAD

**Issue by judahrand** [bytewax/bytewax#171]
**Is your feature request related to a problem? Please describe.**

Tumbling windows are only one sort of window. We need additional window types, for example:

- [ ]  Hopping window #172
- [ ] Sliding window #173
- [ ] Session window #174

These window types are as described here: https://learn.microsoft.com/en-us/azure/stream-analytics/stream-analytics-window-functions

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Psykopear** [comment]
Hi @judahrand , I just merged the latest windowing PR, and they will be in the next release.
There is one difference compared to your issues, as noted in the latest PR (#208): what you called `HoppingWindow` is called a `SlidingWindow` in Flink, and we decided to be consistent with Flink's naming.
Also, the `SlidingWindow` defined in the documentation you linked requires a window to be emitted more than once (every time a window changes), and that's not possible in bytewax currently, so we did not add it.

Something similar could still be implemented, by creating a new window every time an event is received, similarly to a session window, but with a fixed length, and emitted only once.

I'm going to close this issue, but feel free to open a new one if you want to discuss other types of windows.
