### ISSUE TITLE
[FEATURE] Work with Jupyter notebook?

### ISSUE THREAD

**Issue by jimdowling** [bytewax/bytewax#20]
### Bug Description

I tried to run the simple examples from a jupyter notebook but got the following error message.
I didn't have time to look through the source code, but i assume this is some missing default.

---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-1-ded9d2dc59fa> in <module>
     30 flow.inspect(peek)
     31 
---> 32 ec.build_and_run()

Exception: Unrecognized option: 'm'

![image](https://user-images.githubusercontent.com/1904928/154422555-ced4ed00-51d9-47a1-8e6e-15ba4069905b.png)
 

### Python version (`python -V`)

3.8

### Bytewax version (pip list | grep bytewax)

0.7.0

### Relevant log output

```shell
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-1-ded9d2dc59fa> in <module>
     30 flow.inspect(peek)
     31 
---> 32 ec.build_and_run()

Exception: Unrecognized option: 'm'
```

### Steps to Reproduce

Start a jupyter notebook
Run the basic.py code in a notebook, removing the 'if __main__' condition.

**Comment by awmatheson** [comment]
Thanks for opening this! The next release will be notebook compatible working on finalizing some things in #19 to make the experience better in notebooks.

**Comment by awmatheson** [comment]
Notebooks will now work in [release v0.7.1](https://github.com/bytewax/bytewax/releases/tag/v0.7.1). 

Another example notebook - https://github.com/bytewax/bytewax/pull/21
