### ISSUE TITLE
Support Schema Registry

### ISSUE THREAD

**Issue by h-silva** [bytewax/bytewax#202]
I'm using KafkaInputConfig and I need to use schema registry to consume and produce messages in avro in kafka, I'm having a lot of difficulties using it, does it have support? Do we have an example on how to use it?

**Comment by awmatheson** [comment]
Hi @h-silva 👋. Sorry to answer with a few more questions. 

1. Are you using the confluent schema registry? Or something else?
2. Do you have any code examples that are causing you trouble? 

We have left serialization and deserialization reasonably open so the user can bring/adopt their own. So today I think you would need to use the [Python Avro Library](https://avro.apache.org/docs/1.11.1/getting-started-python/) and do the deserialization in a map step after the input. An example of Kafka Input and JSON serialization without a schema registry can be found in the [examples in the repo](https://github.com/bytewax/bytewax/blob/main/examples/simple_kafka_in_and_out.py). Expanding on that, I think you would want to make a request to the schema registry and then use that in the map step with the Python Avro library.
