### ISSUE TITLE
Include `additional_properties` option for KafkaRecoveryConfig 

### ISSUE THREAD

**Issue by MortenSlingsby** [bytewax/bytewax#215]
**Is your feature request related to a problem? Please describe.**
I want to store the state on a Kafka broker that is reachable only through SASL_SSL authentication. Currently the KafkaRecoveryConfig only allows brokers that are reachable without authentication.

**Describe the solution you'd like**
Similar to the KafkaIn/Outputconfig I'd like to be able to include additional properties so I can define SASL username, password, mechanism, etc.

**Describe alternatives you've considered**
Alternative is to spin up a broker separate from my datasource/sink broker and available without authentication. In our case that option is however unfeasible and would lead to additional overhead that needs to be managed.

**Comment by awmatheson** [comment]
Closing this since we stopped supporting KafkaRecovery in the latest releases and we recommend using sqlite based recovery.
