### ISSUE TITLE
CPU usage of workers jumps to 100 percent after input source finishes

### ISSUE THREAD

**Issue by andrewchambers** [bytewax/bytewax#220]
### Bug Description

When using spawn_cluster and you create more workers than 'distribute' is able to allocate work to, the workers that finish early immediately jump to 100 percent cpu usage until the whole job finishes.

This is possibly related to #161 but seems different, because in this case we know for a fact there is no more input.

### Python version (`python -V`)

3.10

### Bytewax version (pip list | grep bytewax)

0.15.1

### Steps to Reproduce

- Spawn a cluster with many more workers than work available to them.
- Have some of your manual input functions exit as they have no more work.
- The cpu usage of those workers with no more input will spike to 100 percent while waiting for other workers to finish.

**Comment by andrewchambers** [comment]
Reproduction:
```
import time
from bytewax.dataflow import Dataflow
from bytewax.inputs import ManualInputConfig
from bytewax.outputs import StdOutputConfig
from bytewax.execution import run_main, spawn_cluster


def input_builder(worker_index, worker_count, resume_state):
    if worker_index != 0:
        return
    i = 0
    while True:
        time.sleep(0.001)
        i += 1
        yield None, i

flow = Dataflow()
flow.input("input", ManualInputConfig(input_builder))
flow.capture(StdOutputConfig())

if __name__ == '__main__':
    spawn_cluster(
        flow,
        proc_count=4,
    )
```

```
 PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                     
 695475 ac        20   0  654192  24928  14208 S 100.0   0.2   0:57.42 python                      
 695476 ac        20   0  654192  24936  14212 S 100.0   0.2   0:57.42 python                      
 695477 ac        20   0  654192  25064  14152 S 100.0   0.2   0:57.45 python 
```

**Comment by andrewchambers** [comment]
Not an expert in timely dataflow, but I noticed once EOF is hit, 'epoch_started' is never updated again which means 'advance' will always be true:

https://github.com/bytewax/bytewax/blob/9e13300aff81857a1131c8fa6e504b4949e1aeda/src/execution/epoch/periodic_epoch.rs#L144

**Comment by davidselassie** [comment]
Yes, this is a manifestation of #161. Specifically the [Timely main loop](https://github.com/bytewax/bytewax/blob/9e13300aff81857a1131c8fa6e504b4949e1aeda/src/execution/mod.rs#L405-L413) part of it: the workers aren't spinning trying to get more input (they do finish) but they are spinning to see if any other operators have work.

I'm going to close this in favor of that other issue, but thank you so much for the simple repro.
