### ISSUE TITLE
[FEATURE] Add support for environment variables in waxctl

### ISSUE THREAD

**Issue by Paulescu** [bytewax/bytewax#223]
## Problem
I am trying to deploy a dataflow to EC2 using waxctl. My Python code is a package, that depends on a couple of environment variables to run.

I tried to pass them to my EC2 runtime by defining them in a `setup-ec2.sh` script, as follows
```
export HOPSWORKS_PROJECT_NAME=my_project_name
export HOPSWORKS_API_KEY=my_api_key
```
and then pass this script as `--system-setup-file-name` parameter.
```
$ waxctl aws deploy project-files.tar \
		-f src/dataflow.py \
		--system-setup-file-name ./setup-ec2.sh \
		--region us-east-1 \
		-t t2.micro \
		--name "bytewax" \
		--python-package \
		--debug
```

However, when I deploy the dataflow, it crashes as soon as I try to fetch these env variables in my Python code using `os.environ['HOPSWORKS_PROJECT_NAME']`

## Ideal solution
Can you make these `export` statement in my `setup-ec2.sh` work?

**Comment by miccioest** [comment]
@Paulescu, we added the parameter `--environment-variables` (short `-E`) to `waxctl v0.7.4` .
Now it's possible to pass the desired environment variables like this:

```bash
waxctl aws deploy dataflow.py --name mydataflow  \
  -E MY_ENV_VAR=somevalue,ANOTHER_ENV_VAR=SOMETHING
```

You should remove the `export` statements from your `setup-ec2.sh`.

Thank you for contributing to Bytewax!
