### ISSUE TITLE
Install the latest version of bytewax with pip.

### ISSUE THREAD

**Issue by ViniciusSabariz** [bytewax/bytewax#252]
### Bug Description

I am unable to install the latest version of bytewax with pip.

When I have to install bytewax with pip install bytewax, the version it installs is 0.11.0

I tried to force version 0.16.1 manually and got the following error:
> ERROR: Could not find a version that satisfies the requirement bytewax==0.16.1 (from versions: 0.6.1, 0.7.0, 0.7.1, 0.8.0b0, 0.8.0b1, 0.8.0b2, 0.8.0, 0.9.0, 0.10.0, 0.10.1, 0.11.0)
> ERROR: No matching distribution found for bytewax==0.16.1

I tried using another environment with python 3.8.10 and got the same problem.

pip version: 23.1.2

### Python version (`python -V`)

Python 3.10.11

### Bytewax version (pip list | grep bytewax)

 bytewax 0.11.0

### Operating System version (`uname -morp`)

Microsoft Windows [10.0.22.621.1702]

### Steps to Reproduce

1. pip install bytewax
![image](https://github.com/bytewax/bytewax/assets/38088170/2ad06bea-c9cd-47f4-b874-a27371c2b2d3)

**Comment by awmatheson** [comment]
Windows builds were dropped due to a rust rdkafka dependency. This should be fixed in the next release with https://github.com/bytewax/bytewax/pull/249

/cc @whoahbot

**Comment by ViniciusSabariz** [comment]
Ok, thanks for the support. I will use linux.

**Comment by Fu-Jie** [comment]
> Bytewax v0.16.2 wheels for windows should now be available on PyPI.

**I had the same problem with centos7 and couldn't update to the latest version.**

![image](https://github.com/bytewax/bytewax/assets/33599649/e52dcd6c-2ff7-40e3-88a1-f585e90f7989)
