### ISSUE TITLE
stdout does not appear when using `KafkaInput`

### ISSUE THREAD

**Issue by mattfysh** [bytewax/bytewax#313]
### Bug Description

A bunch of lines that should print to stdout don't appear in the terminal:

1. `print()`
2. `flow.inspect(print)`
3. `flow.out("stdout", StdOutput())`

### Python version (`python -V`)

using bytewax/bytewax image

### Bytewax version (pip list | grep bytewax)

using bytewax/bytewax image

### Operating System version (`uname -morp`)

using bytewax/bytewax image

### Steps to Reproduce

Reproduction code: https://github.com/mattfysh/cluster_bytewax_stdout

**Comment by mattfysh** [comment]
Thanks to @Psykopear I am able to get stdout working for the second flow when setting `PYTHONUNBUFFERED=1` env var

I am curious to understand why this setting is needed for the second flow with `KafkaInput`, and not for the first using `FileInput`. Feel free to close this issue if you like, now that a solution is available

**Comment by Psykopear** [comment]
Thanks for updating the issue.
Yes I'd expect it to either happen or not with both, it is indeed interesting that it only happens with KafkaInput only in your case, but good to know it worked.
